import { NextResponse } from 'next/server';
import fs from 'fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import { getItemData } from '../../../../_src/utils/itemsData';
import { getMinecraftTextureKey } from '../../../../_src/utils/items/minecraftFallback';

// Item texture image (used by the Discord bot):
//   /api/v1/items/texture?name=<item name>
// Animated items are served EXCLUSIVELY from the prerendered GIFs at
// public/spritesheets/textures/<token>.gif (generated by the spritesheet
// import); there is no on-demand encoder. Static items are cropped from the
// sheets on request, with a vanilla Minecraft texture fallback for items
// without a custom sprite.
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const CELL = 64;
const TEXTURE_DIR = path.join(process.cwd(), 'public', 'spritesheets', 'textures');

let spriteInfo = null;

async function getSpriteInfo() {
    if (spriteInfo) return spriteInfo;
    const base = path.join(process.cwd(), 'public', 'spritesheets');
    const [mapRaw, cssRaw, sheet, animSheet, mcCssRaw, mcSheet] = await Promise.all([
        fs.readFile(path.join(base, 'itemsheet-map.json'), 'utf8'),
        fs.readFile(path.join(base, '_itemsheet.css'), 'utf8'),
        fs.readFile(path.join(base, 'itemsheet.png')),
        fs.readFile(path.join(base, 'itemsheet-anim.png')),
        fs.readFile(path.join(base, '_minecraft.css'), 'utf8'),
        fs.readFile(path.join(base, 'minecraft.png')),
    ]);

    const map = JSON.parse(mapRaw);

    // Sprite position per token (background-position, negated).
    const positions = {};
    const re = /\.monumenta-([\w-]+)\s*\{\s*background-position:\s*(-?\d+)px\s+(-?\d+)px/g;
    let m;
    while ((m = re.exec(cssRaw))) {
        positions[m[1]] = { x: Math.abs(Number(m[2])), y: Math.abs(Number(m[3])) };
    }

    // Animated textures: the per-item @keyframes strip lists every frame's
    // position (percent of the total duration + x/y offset). Uniform strips
    // (equal dwells) are emitted as `animation: ... Xms steps(N, end)
    // infinite` with from/to keyframes instead, so those are synthesised
    // from the strip start + pitch below.
    //
    // The keyframes block contains nested braces (one { } per frame), so it
    // is matched with a brace-pair pattern - a plain [\s\S]*? would stop at
    // the first frame's closing brace and yield a single-frame animation.
    const animFrames = {};
    const kr = /@keyframes\s+sts-anim-([\w-]+)\s*\{((?:[^{}]|\{[^{}]*\})*)\}/g;
    while ((m = kr.exec(cssRaw))) {
        const frames = [];
        const fr = /(\d+(?:\.\d+)?%)\s*\{\s*background-position:\s*(-?\d+)px\s+(-?\d+)px/g;
        let f;
        while ((f = fr.exec(m[2]))) {
            frames.push({ pct: parseFloat(f[1]), x: Math.abs(Number(f[2])), y: Math.abs(Number(f[3])) });
        }
        if (frames.length > 0) {
            frames.sort((a, b) => a.pct - b.pct);
            animFrames[m[1]] = frames;
        }
    }

    // Total animation duration per token (from `animation: ... Xms infinite`).
    const durations = {};
    const dr = /animation:\s*sts-anim-([\w-]+)\s+(\d+)ms/g;
    while ((m = dr.exec(cssRaw))) {
        durations[m[1]] = Number(m[2]);
    }

    // Uniform strips: `animation: sts-anim-X 2400ms steps(48, end) infinite`.
    // Frames sit side by side, SPRITE_SIZE + 2 = 66px apart (the generator's
    // strip pitch).
    const STRIP_PITCH = 66;
    const ur = /animation:\s*sts-anim-([\w-]+)\s+(\d+)ms steps\((\d+),\s*end\) infinite/g;
    while ((m = ur.exec(cssRaw))) {
        const token = m[1];
        if (animFrames[token]) continue; // variable keyframes already parsed
        const count = Number(m[3]);
        const pos = positions[token];
        if (count >= 2 && pos) {
            const frames = [];
            for (let i = 0; i < count; i++) {
                frames.push({ pct: (i / count) * 100, x: pos.x + i * STRIP_PITCH, y: pos.y });
            }
            animFrames[token] = frames;
        }
    }

    const mcPositions = {};
    const mcRe = /\.minecraft-([\w-]+)\s*\{\s*background-position:\s*(-?\d+)px\s+(-?\d+)(?:px)?/g;
    while ((m = mcRe.exec(mcCssRaw))) {
        mcPositions[m[1]] = { x: Math.abs(Number(m[2])), y: Math.abs(Number(m[3])) };
    }

    spriteInfo = { map, positions, animFrames, durations, sheet, animSheet, mcPositions, mcSheet };
    return spriteInfo;
}

function findSpriteKey(map, itemKey, itemName) {
    const candidates = [
        itemName,
        itemName && itemName.replace(/^EX\s+/, ''),
        itemKey,
        itemKey && itemKey.replace(/^EX\s+/, ''),
        itemKey && itemKey.replace(/-[0-9]+$/, ''),
    ];
    for (const c of candidates) {
        if (c && map[c]) return map[c];
    }
    return null;
}

const imageCache = new Map();

async function renderStatic(sheet, pos) {
    const key = 's' + pos.x + 'x' + pos.y;
    if (imageCache.has(key)) return imageCache.get(key);
    const buf = await sharp(sheet, { limitInputPixels: false })
        .extract({ left: pos.x, top: pos.y, width: CELL, height: CELL })
        .resize(CELL * 2, CELL * 2, { kernel: sharp.kernel.nearest })
        .png()
        .toBuffer();
    imageCache.set(key, buf);
    return buf;
}

export async function GET(request) {
    const { searchParams } = new URL(request.url);
    const name = (searchParams.get('name') || '').trim();
    if (!name) {
        return NextResponse.json({ error: 'missing name' }, { status: 400 });
    }
    const debug = searchParams.get('debug') === '1';

    const itemData = await getItemData();
    const item = itemData[name] || Object.values(itemData).find((i) => i.name === name) || null;
    const info = await getSpriteInfo();
    const spriteKey = findSpriteKey(info.map, name, name);
    const frames = spriteKey ? info.animFrames[spriteKey] : null;

    let body;
    let contentType;
    let servedFrom = null;
    if (spriteKey && frames) {
        // Animated items come exclusively from the prerendered GIFs (the
        // spritesheet import writes textures/<token>.gif for every animated
        // item). No on-demand encoder: a missing file means the import for
        // this spritesheet revision didn't run.
        const pre = path.join(TEXTURE_DIR, `${spriteKey}.gif`);
        try {
            body = await fs.readFile(pre);
        } catch (e) {
            return NextResponse.json({ error: 'no prerendered texture for item' }, { status: 404 });
        }
        servedFrom = `textures/${spriteKey}.gif`;
        contentType = 'image/gif';
    } else {
        let pos = spriteKey && info.positions[spriteKey];
        let sheet = info.sheet;
        // Fall back to the vanilla Minecraft texture for the base material.
        if (!pos && item && item.base_item) {
            const mcKey = getMinecraftTextureKey(item.base_item);
            const mcPos = info.mcPositions[mcKey];
            if (mcPos) {
                pos = mcPos;
                sheet = info.mcSheet;
            }
        }
        if (!pos) {
            return NextResponse.json({ error: 'no texture for item' }, { status: 404 });
        }
        body = await renderStatic(sheet, pos);
        contentType = 'image/png';
    }

    if (debug) {
        const pos = spriteKey ? info.positions[spriteKey] : null;
        return NextResponse.json({
            name,
            spriteToken: spriteKey,
            position: pos || null,
            animated: Boolean(frames && frames.length > 1),
            frameCount: frames ? frames.length : 1,
            durationMs: spriteKey ? info.durations[spriteKey] || null : null,
            frames: (frames || []).map((f, i) => ({ index: i, x: f.x, y: f.y, pct: f.pct })),
            contentType,
            servedFrom,
            gifBytes: contentType === 'image/gif' ? body.length : null,
        });
    }

    return new NextResponse(body, {
        headers: {
            'Content-Type': contentType,
            'Cache-Control': 'public, max-age=86400',
        },
    });
}
